### PR TITLE
return an order

### PR DESCRIPTION
**Pull request by charlotte-waegeneire**
/!\ in the api route, I don't update the product quantity since it's more logical for the employees to do so once they get the product back

### CODE REVIEW

**Review by william-wtr92 — COMMENTED** [review]
- fix category unit test
- when we go on return page we have this error : Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
-on an order with several items I can't send back just one, I have to select them all

**Review by william-wtr92 — COMMENTED** [review]
- fix front error in confirmation
- fix api confirmOrder

**Comment by charlotte-waegeneire** [comment]
I cleared my cache, ran the migrations and the seeds but I didn't get your errors. please do so and try again

**Comment by charlotte-waegeneire** [comment]
ui/ux review ticket (ref412) : https://planning-project-sdv.atlassian.net/browse/SDV-412?atlOrigin=eyJpIjoiM2VlZGM4NWVlZjJhNDAyMThmMmYwMjQ5NzkwNWIyNjciLCJwIjoiaiJ9

**Review by william-wtr92 — APPROVED** [review]
ok good

**Pull request merged**
