### PR TITLE
SDV-362 carousel-product

### PR DESCRIPTION
**Pull request by ShinoTetsu**

### CODE REVIEW

**Review by william-wtr92 — COMMENTED** [review]
- régler produits similaires, promotions

**Comment by charlotte-waegeneire** [comment]
even without modifying anything it's not working:

error    [ 'body.image must be a `string` type, but the final value was: `[\n {\n "url": "\\"http://placeimg.com/640/480\\""\n },\n {\n "url": "\\"https://images.unsplash.com/photo-1630699144339-420f59b4747b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80\\""\n },\n {\n "url": "\\"http://placeimg.com/640/480\\""\n },\n {\n "url": "\\"https://images.unsplash.com/photo-1630699144339-420f59b4747b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80\\""\n }\n]`.' ]

**Review by william-wtr92 — COMMENTED** [review]
- http://localhost:3000/fr/categories/[id]/category pas de photos des produits dans cette affichage

**Comment by charlotte-waegeneire** [comment]
you made a try/catch but you're not using it...

UniqueViolationError: insert into "product" ("categoryId", "description", "image", "materialId", "name", "price", "promotion", "quantity") values ($1, $2, $3, $4, $5, $6, $7, $8) returning "id" - duplicate key value violates unique constraint "product_pkey"

**Pull request merged**
